server:
  port: 9666
  # 开启优雅停机
  shutdown: graceful

spring:
  application:
    name: amour
  lifecycle:
    # 优雅停机最大等待时间
    timeout-per-shutdown-phase: 60s
  profiles:
    active: dev

# logback日志配置
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} [${spring.profiles.active}] [%X{traceId:-}] %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5p} ${PID:- } --- [%t] [${spring.profiles.active}] [%X{traceId:-}] %-40.40logger{39} : %m%n'
  file:
    name: ./logs/${spring.application.name}_${spring.profiles.active}.log
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.name}.%d.%i.log
      max-file-size: 100MB
      max-history: 180
  level:
    org.zalando.logbook.Logbook: TRACE

# mybatis-flex配置
mybatis-flex:
  global-config:
    key-config:
      key-type: generator
      value: snowFlakeId
    logic-delete-column: del_flag

# Logbook配置
logbook:
  write:
    # body 最大记录长度，超出部分用 ... 截断
    max-body-size: 2000
  obfuscate:
    # 混淆内容替换字符串
    replacement: "***"
    # 需要混淆的 HTTP Header 名称列表
    headers:
      - Authorization
      - cookie
      - Set-Cookie
    # 需要混淆的 JSON Body 字段名称列表
    json-body-fields:
      - accessToken
      - password
      - oldPassword
      - newPassword
      - confirmPassword
